package net.prismc.prisbungeehandler.files.loader;

import net.prismc.prisbungeehandler.files.configs.Config;

import java.util.ArrayList;
import java.util.List;

public class ConfigLoader {
    private final Config config;

    public ConfigLoader(Config config) {
        this.config = config;
    }

    /**
     * Loads the values into the specified config file
     */
    public void loadMessages() {

        // Database Main
        config.getConfig().set("MySQL.Host", "your_database");
        config.getConfig().set("MySQL.Port", "3306");
        config.getConfig().set("MySQL.Username", "username");
        config.getConfig().set("MySQL.Password", "password");
        config.getConfig().set("MySQL.Database", "prismc");

        // Database Other
        config.getConfig().set("MySQL.cachePrepStmts", true);
        config.getConfig().set("MySQL.prepStmtCacheSize", 250);
        config.getConfig().set("MySQL.prepStmtCacheSqlLimit", 2048);
        config.getConfig().set("MySQL.useServerPrepStmts", true);
        config.getConfig().set("MySQL.useLocalSessionState", true);
        config.getConfig().set("MySQL.rewriteBatchedStatements", true);
        config.getConfig().set("MySQL.cacheResultSetMetadata", true);
        config.getConfig().set("MySQL.cacheServerConfiguration", true);
        config.getConfig().set("MySQL.elideSetAutoCommits", false);
        config.getConfig().set("MySQL.maintainTimeStats", false);
        config.getConfig().set("MySQL.maximumPoolSize", 10);
        config.getConfig().set("MySQL.leakDetectionThreshold", 60000);

        // Swear Lists
        config.getConfig().set("Filter.HIGH", getList("high"));
        config.getConfig().set("Filter.MEDIUM", getList("medium"));
        config.getConfig().set("Filter.LOW", getList("low"));

        config.saveConfig();
        config.reloadConfig();
    }

    private List<String> getList(String type) {
        List<String> list = new ArrayList<>();

        switch (type) {
            case "high":
                list.add("[EXACT] ass");
                list.add("[EXACT] butt");
                list.add("[EXACT] cock");
                list.add("[EXACT] cum");
                list.add("[EXACT] cunt");
                list.add("[EXACT] nude");
                list.add("[EXACT] tit");
                list.add("[STRING] ball gag");
                list.add("[STRING] ball gravy");
                list.add("[STRING] ball kicking");
                list.add("[STRING] ball licking");
                list.add("[STRING] ball sack");
                list.add("[STRING] ball sucking");
                list.add("[STRING] barely legal");
                list.add("[STRING] big black");
                list.add("[STRING] big breasts");
                list.add("[STRING] big knockers");
                list.add("[STRING] big tits");
                list.add("[STRING] black cock");
                list.add("[STRING] fuck buttons");
                list.add("[STRING] fudge packer");
                list.add("[STRING] gay sex");
                list.add("[STRING] giant cock");
                list.add("[STRING] god damn");
                list.add("[STRING] jelly donut");
                list.add("[STRING] make me come");
                list.add("[STRING] nsfw images");
                list.add("[STRING] piece of shit");
                list.add("[STRING] strip club");
                list.add("[STRING] tea bagging");
                list.add("anus");
                list.add("apeshit");
                list.add("arsehole");
                list.add("asshole");
                list.add("babeland");
                list.add("barenaked");
                list.add("bastard");
                list.add("bastardo");
                list.add("beaner");
                list.add("beaners");
                list.add("boner");
                list.add("boob");
                list.add("busty");
                list.add("buttcheeks");
                list.add("butthole");
                list.add("cocks");
                list.add("crap");
                list.add("damn");
                list.add("escort");
                list.add("genitals");
                list.add("kinky");
                list.add("nsfw");
                list.add("nudity");
                list.add("panties");
                list.add("penis");
                list.add("sex");
                list.add("shrimping");
                list.add("suck");
                list.add("tits");
                list.add("titties");
                list.add("titty");
                list.add("wtf");
                return list;

            case "medium":
                list.add("[EXACT] anal");
                list.add("assmunch");
                list.add("bimbos");
                list.add("bitch");
                list.add("bitches");
                list.add("blowjob");
                list.add("bullshit");
                list.add("cumming");
                list.add("dick");
                list.add("fuck");
                list.add("fudgepacker");
                list.add("horny");
                list.add("humping");
                list.add("intercourse");
                list.add("jizz");
                list.add("juggs");
                list.add("masturbate");
                list.add("masturbating");
                list.add("masturbation");
                list.add("milf");
                list.add("motherfucker");
                list.add("porn");
                list.add("porno");
                list.add("pornography");
                list.add("sexcam");
                list.add("sexo");
                list.add("sexual");
                list.add("sexuality");
                list.add("sexually");
                list.add("sexy");
                list.add("shit");
                list.add("shitblimp");
                list.add("shitty");
                list.add("threesome");
                list.add("topless");
                list.add("tushy");
                list.add("vagina");
                list.add("whore");
                return list;

            case "low":
                list.add("[EXACT] clit");
                list.add("[EXACT] coon");
                list.add("[EXACT] fag");
                list.add("[EXACT] orgy");
                list.add("[EXACT] poof");
                list.add("[EXACT] poon");
                list.add("[EXACT] smut");
                list.add("[EXACT] wank");
                list.add("[EXACT] xx");
                list.add("[EXACT] xxx");
                list.add("[STRING] 2 girls 1 cup");
                list.add("[STRING] alabama hot pocket");
                list.add("[STRING] alaskan pipeline");
                list.add("[STRING] auto erotic");
                list.add("[STRING] baby batter");
                list.add("[STRING] baby juice");
                list.add("[STRING] beaver cleaver");
                list.add("[STRING] beaver lips");
                list.add("[STRING] blonde action");
                list.add("[STRING] blonde on blonde action");
                list.add("[STRING] blow job");
                list.add("[STRING] blow your load");
                list.add("[STRING] blue waffle");
                list.add("[STRING] booty call");
                list.add("[STRING] brown showers");
                list.add("[STRING] brunette action");
                list.add("[STRING] bullet vibe");
                list.add("[STRING] bung hole");
                list.add("[STRING] camel toe");
                list.add("[STRING] carpet muncher");
                list.add("[STRING] chocolate rosebuds");
                list.add("[STRING] cleveland steamer");
                list.add("[STRING] clover clamps");
                list.add("[STRING] date rape");
                list.add("[STRING] deep throat");
                list.add("[STRING] dirty pillows");
                list.add("[STRING] dirty sanchez");
                list.add("[STRING] dog style");
                list.add("[STRING] doggie style");
                list.add("[STRING] doggy style");
                list.add("[STRING] doggystyle");
                list.add("[STRING] donkey punch");
                list.add("[STRING] double dong");
                list.add("[STRING] double penetration");
                list.add("[STRING] dp action");
                list.add("[STRING] dry hump");
                list.add("[STRING] eat my ass");
                list.add("[STRING] female squirting");
                list.add("[STRING] foot fetish");
                list.add("[STRING] gang bang");
                list.add("[STRING] girl on top");
                list.add("[STRING] girl on");
                list.add("[STRING] girls gone wild");
                list.add("[STRING] golden shower");
                list.add("[STRING] goo girl");
                list.add("[STRING] group sex");
                list.add("[STRING] hand job");
                list.add("[STRING] hard core");
                list.add("[STRING] hot carl");
                list.add("[STRING] hot chick");
                list.add("[STRING] how to kill");
                list.add("[STRING] how to murder");
                list.add("[STRING] jack off");
                list.add("[STRING] jail bait");
                list.add("[STRING] jerk off");
                list.add("[STRING] leather restraint");
                list.add("[STRING] leather straight jacket");
                list.add("[STRING] lemon party");
                list.add("[STRING] male squirting");
                list.add("[STRING] menage a trois");
                list.add("[STRING] missionary position");
                list.add("[STRING] mound of venus");
                list.add("[STRING] mr hands");
                list.add("[STRING] muff diver");
                list.add("[STRING] nig nog");
                list.add("[STRING] one cup two girls");
                list.add("[STRING] one guy one jar");
                list.add("[STRING] phone sex");
                list.add("[STRING] piss pig");
                list.add("[STRING] pleasure chest");
                list.add("[STRING] pole smoker");
                list.add("[STRING] poop chute");
                list.add("[STRING] prince albert piercing");
                list.add("[STRING] raging boner");
                list.add("[STRING] reverse cowgirl");
                list.add("[STRING] rosy palm and her 5 sisters");
                list.add("[STRING] rosy palm");
                list.add("[STRING] rusty trombone");
                list.add("[STRING] shaved beaver");
                list.add("[STRING] shaved pussy");
                list.add("[STRING] splooge moose");
                list.add("[STRING] spooge");
                list.add("[STRING] spread legs");
                list.add("[STRING] strap on");
                list.add("[STRING] style doggy");
                list.add("[STRING] suck my dick");
                list.add("[STRING] suicide girls");
                list.add("[STRING] sultry women");
                list.add("[STRING] tainted love");
                list.add("[STRING] taste my");
                list.add("[STRING] tied up");
                list.add("[STRING] tight white");
                list.add("[STRING] tongue in a");
                list.add("[STRING] tub girl");
                list.add("[STRING] two girls one cup");
                list.add("[STRING] urethra play");
                list.add("[STRING] venus mound");
                list.add("[STRING] violet wand");
                list.add("[STRING] wet dream");
                list.add("[STRING] white power");
                list.add("[STRING] wrapping men");
                list.add("[STRING] wrinkled starfish");
                list.add("[STRING] yellow showers");
                list.add("2g1c");
                list.add("acrotomophilia");
                list.add("anilingus");
                list.add("autoerotic");
                list.add("bangbros");
                list.add("bangbus");
                list.add("bareback");
                list.add("bastinado");
                list.add("bbw");
                list.add("bdsm");
                list.add("beastiality");
                list.add("bestiality");
                list.add("birdlock");
                list.add("blumpkin");
                list.add("bollocks");
                list.add("bondage");
                list.add("bukkake");
                list.add("bulldyke");
                list.add("bunghole");
                list.add("camgirl");
                list.add("camslut");
                list.add("camwhore");
                list.add("carpetmuncher");
                list.add("cialis");
                list.add("circlejerk");
                list.add("clitoris");
                list.add("clusterfuck");
                list.add("coons");
                list.add("coprolagnia");
                list.add("coprophilia");
                list.add("cornhole");
                list.add("creampie");
                list.add("cumshot");
                list.add("cumshots");
                list.add("cunnilingus");
                list.add("darkie");
                list.add("daterape");
                list.add("deepthroat");
                list.add("dendrophilia");
                list.add("dildo");
                list.add("dingleberries");
                list.add("dingleberry");
                list.add("doggiestyle");
                list.add("dolcett");
                list.add("domination");
                list.add("dominatrix");
                list.add("dommes");
                list.add("dvda");
                list.add("ecchi");
                list.add("ejaculation");
                list.add("erotic");
                list.add("erotism");
                list.add("eunuch");
                list.add("faggot");
                list.add("fecal");
                list.add("felch");
                list.add("fellatio");
                list.add("feltch");
                list.add("femdom");
                list.add("figging");
                list.add("fingerbang");
                list.add("fingering");
                list.add("fisting");
                list.add("footjob");
                list.add("frotting");
                list.add("futanari");
                list.add("g-spot");
                list.add("gangbang");
                list.add("goatcx");
                list.add("goatse");
                list.add("gokkun");
                list.add("goodpoop");
                list.add("goregasm");
                list.add("grope");
                list.add("gspot");
                list.add("guro");
                list.add("handjob");
                list.add("hardcore");
                list.add("hentai");
                list.add("homoerotic");
                list.add("honkey");
                list.add("hooker");
                list.add("incest");
                list.add("jailbait");
                list.add("jigaboo");
                list.add("jiggaboo");
                list.add("jiggerboo");
                list.add("kike");
                list.add("kinbaku");
                list.add("kinkster");
                list.add("knobbing");
                list.add("livesex");
                list.add("lolita");
                list.add("lovemaking");
                list.add("mong");
                list.add("muffdiving");
                list.add("nambla");
                list.add("nawashi");
                list.add("negro");
                list.add("neonazi");
                list.add("nigga");
                list.add("nigger");
                list.add("nimphomania");
                list.add("nipple");
                list.add("nutten");
                list.add("nympho");
                list.add("nymphomania");
                list.add("octopussy");
                list.add("omorashi");
                list.add("orgasm");
                list.add("paedophile");
                list.add("paki");
                list.add("panty");
                list.add("pedobear");
                list.add("pedophile");
                list.add("pegging");
                list.add("pikey");
                list.add("pissing");
                list.add("pisspig");
                list.add("playboy");
                list.add("ponyplay");
                list.add("poontang");
                list.add("poopchute");
                list.add("pthc");
                list.add("pubes");
                list.add("punany");
                list.add("pussy");
                list.add("queaf");
                list.add("queef");
                list.add("quim");
                list.add("raghead");
                list.add("rape");
                list.add("raping");
                list.add("rapist");
                list.add("rectum");
                list.add("rimjob");
                list.add("rimming");
                list.add("s&m");
                list.add("sadism");
                list.add("santorum");
                list.add("scat");
                list.add("schlong");
                list.add("scissoring");
                list.add("semen");
                list.add("shemale");
                list.add("shibari");
                list.add("shota");
                list.add("skeet");
                list.add("slanteye");
                list.add("slut");
                list.add("snatch");
                list.add("snowballing");
                list.add("sodomize");
                list.add("sodomy");
                list.add("spastic");
                list.add("spic");
                list.add("splooge");
                list.add("spunk");
                list.add("strapon");
                list.add("strappado");
                list.add("swastika");
                list.add("swinger");
                list.add("throating");
                list.add("thumbzilla");
                list.add("tosser");
                list.add("towelhead");
                list.add("tranny");
                list.add("tribadism");
                list.add("tubgirl");
                list.add("twat");
                list.add("twink");
                list.add("twinkie");
                list.add("undressing");
                list.add("upskirt");
                list.add("urophilia");
                list.add("viagra");
                list.add("vibrator");
                list.add("vorarephilia");
                list.add("voyeur");
                list.add("voyeurweb");
                list.add("voyuer");
                list.add("vulva");
                list.add("wetback");
                list.add("worldsex");
                list.add("yaoi");
                list.add("yiffy");
                list.add("zoophilia");
                return list;
        }
        return list;
    }

}
